### ISSUE TITLE
Can't use Protractor $ and $$ shortcuts on calls to this within Extended Class

### ISSUE THREAD

**Issue by codybarr** [Xotabu4/protractor-element-extend#10]
For example:
```
class Select extends BaseFragment {
    constructor(element) {
        super(element);
    }

    selectOption(text) {
        this.element(by.cssContainingText('option', text)).click();
    }

    getSelectedText() {
    	// NOTE: Apparently you can't use the shorthand element locators ($ and $$) with this package.
        // e.g. return this.$('select').getAttribute('value')

        return this.element(by.css('select')).getAttribute('value')
            .then((index) => {
                return this.element(by.css(`option[value="${index}"]`)).getText();
            });
    }
}
```

You have to use ```this.element(by.css(...))```. You can't use ```this.$(...)```

**Comment by Xotabu4** [comment]
@codybarr Thanks! Could you also share your protractor and node version? I will take a look today

**Comment by Xotabu4** [comment]
@codybarr Hi again. I checked this issue, but i can't reproduce it. Works fine on protractor 5.1 and node 7.8

Could you please share error that you are getting when you are trying to use this.$ and this.$$ ?


Here is my experiment:
https://github.com/Xotabu4/Protractor-Experiments/blob/master/experiments/pagefragments/experiment.ts#L44

**Comment by codybarr** [comment]
Hi @Xotabu4, thanks for the quick reply. I'm using `node 7.7.4` and `protractor 5.1.1`

Here's the error I'm getting:

```
Message:
    Failed: Invalid locator
  Stack:
    TypeError: Invalid locator
        at Object.check [as checkedLocator] (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/by.js:267:9)
        at WebElement.findElements (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1983:18)
        at /Users/cody/Projects/{...}/node_modules/protractor/built/element.js:184:46
        at Array.map (native)
        at /Users/cody/Projects/{...}/node_modules/protractor/built/element.js:181:65
        at ManagedPromise.invokeCallback_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    Error
        at ElementArrayFinder.applyAction_ (/Users/cody/Projects/{...}/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as getAttribute] (/Users/cody/Projects/{...}/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as getAttribute] (/Users/cody/Projects/{...}/node_modules/protractor/built/element.js:829:22)
        at Select.getSelectedText (/Users/cody/Projects/{...}/e2e_tests/helper.js:50:33)
        at Object.it (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:53:63)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:110:25
        at new ManagedPromise (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    
    From: Task: Run it("Customer should be able to specify the campaign ends at a certain date/time") in control flow
        at Object.<anonymous> (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2565:10)
        at shutdownTask_.MicroTask (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2490:53)
        at MicroTask.asyncRun (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2619:9)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    
    From asynchronous test: 
    Error
        at Suite.describe (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:43:9)
        at Suite.describe (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:36:5)
        at Object.<anonymous> (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:10:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasmine/lib/jasmine.js:87:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasmine/lib/jasmine.js:86:18)
        at Jasmine.execute (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasmine/lib/jasmine.js:181:8)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:682:9)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:796:13)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:556:49
        at runSingle (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:137:13)
        at flush (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
```

And the corresponding extended class:

```
class Select extends BaseFragment {
    constructor(element) {
        super(element);
    }

    selectOption(text) {
        this.element(by.cssContainingText('option', text)).click();
    }

    getSelectedText() {
    	// NOTE: Apparently you can't use the shorthand element locators ($ and $$) with this package.
        return this.$('select').getAttribute('value')
            .then((index) => {
                return this.element(by.css(`option[value="${index}"]`)).getText();
            });
    }
}
```

I should note I'm not using typescript.

**Comment by Xotabu4** [comment]
@codybarr thanks! Such a weird bug! Looking for root cause. This is pretty strange since i was 100% sure that $ and by.css should be absolutely identical.

Also i got this error 2-3 times, and then it disappear :) I will keep eye on this and try to fix as fast as i will understand what happens

I compared parameters that come to `check` function - and they looks the same:
```
Plain nested call
$$$$$$ GOT LOCATOR! name(name) {
    return By.css('*[name="' + escapeCss(name) + '"]');
  } { using: 'css selector', value: 'select' }
$$$$$$ is function  false


With fragment and this.$:
$$$$$$ GOT LOCATOR! name(name) {
    return By.css('*[name="' + escapeCss(name) + '"]');
  } { using: 'css selector', value: 'select' }
$$$$$$ is function  false


With By.css
$$$$$ GOT LOCATOR! name(name) {
    return By.css('*[name="' + escapeCss(name) + '"]');
  } { using: 'css selector', value: 'select' }
$$$$$$ is function  false
```
